/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package robert.translation.database;

import javax.swing.table.DefaultTableModel;

import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Hawk9
 */
public class TableGUITest extends javax.swing.JFrame
{

  public TableGUITest()
  {

    initComponents();
    jKundenTabelle.setShowGrid(true);
    setSize(1500, 1000);

    int rowc = jKundenTabelle.getRowCount();
    String row = Integer.toString(rowc);
    lRowCount.setText(row);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jPanel1 = new javax.swing.JPanel();
    btAdd = new javax.swing.JButton();
    btRemove = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    lRowCount = new javax.swing.JLabel();
    jScrollPane = new javax.swing.JScrollPane();
    jKundenTabelle = new javax.swing.JTable();
    btUp = new javax.swing.JButton();
    btDown = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    btAdd.setText("Add");
    btAdd.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        btAddActionPerformed(evt);
      }
    });

    btRemove.setText("Remove");
    btRemove.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        btRemoveActionPerformed(evt);
      }
    });

    jLabel1.setText("Rows:");

    lRowCount.setText("0");

    jKundenTabelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jKundenTabelle.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {
        {null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null}
      },
      new String []
      {
        "KKZ", "KName", "KName2", "KAdr1", "KAdr2", "PLZ/Ort", "Land", "Tel.", "UID"
      }
    ));
    jKundenTabelle.setToolTipText("");
    jKundenTabelle.setGridColor(new java.awt.Color(0, 0, 0));
    jKundenTabelle.setRowHeight(30);
    jKundenTabelle.setRowSelectionAllowed(false);
    jKundenTabelle.setSelectionBackground(new java.awt.Color(255, 255, 204));
    jKundenTabelle.getTableHeader().setReorderingAllowed(false);
    jScrollPane.setViewportView(jKundenTabelle);
    if (jKundenTabelle.getColumnModel().getColumnCount() > 0)
    {
      jKundenTabelle.getColumnModel().getColumn(0).setResizable(false);
      jKundenTabelle.getColumnModel().getColumn(1).setResizable(false);
      jKundenTabelle.getColumnModel().getColumn(2).setResizable(false);
      jKundenTabelle.getColumnModel().getColumn(3).setResizable(false);
      jKundenTabelle.getColumnModel().getColumn(4).setResizable(false);
      jKundenTabelle.getColumnModel().getColumn(5).setResizable(false);
      jKundenTabelle.getColumnModel().getColumn(6).setResizable(false);
      jKundenTabelle.getColumnModel().getColumn(7).setResizable(false);
    }

    btUp.setText("Up");
    btUp.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        btUpActionPerformed(evt);
      }
    });

    btDown.setText("Down");
    btDown.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        btDownActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addGap(6, 6, 6)
        .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btUp)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btDown)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
        .addComponent(jLabel1)
        .addGap(2, 2, 2)
        .addComponent(lRowCount)
        .addGap(40, 40, 40))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btAdd)
          .addComponent(btRemove)
          .addComponent(btUp)
          .addComponent(btDown)
          .addComponent(jLabel1)
          .addComponent(lRowCount))
        .addContainerGap())
    );

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
      DefaultTableModel model = (DefaultTableModel) jKundenTabelle.getModel();
      model.addRow(new Object[]
      {
      });
      int rowc = jKundenTabelle.getRowCount();
      String row = Integer.toString(rowc);
      lRowCount.setText(row);
    }//GEN-LAST:event_btAddActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
      DefaultTableModel model = (DefaultTableModel) jKundenTabelle.getModel();
      int[] rows = jKundenTabelle.getSelectedRows();
      for (int i = 0; i < rows.length; i++)
      {
        model.removeRow(rows[i] - i);
      }
      int rowc = jKundenTabelle.getRowCount();
      String row = Integer.toString(rowc);
      lRowCount.setText(row);

    }//GEN-LAST:event_btRemoveActionPerformed

    private void btUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpActionPerformed
      DefaultTableModel model = (DefaultTableModel) jKundenTabelle.getModel();
      int[] rows = jKundenTabelle.getSelectedRows();
      model.moveRow(rows[0], rows[rows.length - 1], rows[0] - 1);
      jKundenTabelle.setRowSelectionInterval(rows[0] - 1, rows[rows.length - 1] - 1);
    }//GEN-LAST:event_btUpActionPerformed

    private void btDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDownActionPerformed
      DefaultTableModel model = (DefaultTableModel) jKundenTabelle.getModel();
      int[] rows = jKundenTabelle.getSelectedRows();
      model.moveRow(rows[0], rows[rows.length - 1], rows[0] + 1);
      jKundenTabelle.setRowSelectionInterval(rows[0] + 1, rows[rows.length - 1] + 1);
    }//GEN-LAST:event_btDownActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(TableGUITest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(TableGUITest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(TableGUITest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(TableGUITest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
        //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
        //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
        //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new TableGUITest().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btAdd;
  private javax.swing.JButton btDown;
  private javax.swing.JButton btRemove;
  private javax.swing.JButton btUp;
  private javax.swing.JTable jKundenTabelle;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane;
  private javax.swing.JLabel lRowCount;
  // End of variables declaration//GEN-END:variables

}
